### ISSUE TITLE
[질문] filter함수를 사용해도 undefined를 잘 걸러낼 수 있다

### ISSUE THREAD

**Issue by soyeon102** [DD-BS/Effective-TypeScript#1]
page : 127

### 이해가 안 되는 내용

책에서는 'filter 함수를 사용해 `undefined`를 걸러 내려고 해도 잘 동작하지 않을 겁니다.' 라고 쓰여있다. 그러나 실제로 아래 코드를 실행해보면 `undefined`는 잘 걸러져서 나온다.

### 관련 코드 또는 예제
```ts
const arr1 = ["A", "B", "C"];
const members = ["A", "B"]
  .map((who) => arr1.find((el) => el === who))
  .filter((who) => who !== undefined);

```
![image](https://github.com/user-attachments/assets/0e025ef3-f52e-47bc-8b0c-dbd51c12b8a8)

### 추가적인 부가 설명
책 내용대로라면 members타입이 `(string | undefined)[]`로 나와야 하지만, 실제로 편집기에서 members타입은 `string[]`으로 정상적으로 나온다. 이런 경우에는 굳이 타입 가드를 사용하지 않고도 filter함수만으로 `undefined`를 걸러낼 수 있는 것 아닌가?

**Comment by lionleeee** [comment]
[관련 링크](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-5.html)
- 타입스크립트 5.5 릴리즈에서 filter 관련된 타입 체크가 개선 되었음
- ** 책에서는 3.8.2 버전 사용  
![image](https://github.com/user-attachments/assets/3ed78f2e-b65d-45fa-bbab-de272f907362)
